import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import HomePage from "@/src/components/home/home-page";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ data }) {
  const [events, setEvents] = useState(data);
  const [text, setText] = useState("");

  const submit = async (e) => {
    e.preventDefault();
    const newObj = {
      id: text,
      title: `Events in ${text}`,
      description: `Ut enim ad minima veniam, quis nostrum exercitation`,
      image: `https://source.unsplash.com/random/400x20`,
    };

    const res = await fetch("/api/addEvent", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify(newObj),
    });

    const data = await res.json();
    console.log(data);
    /*     setEvents([...events, newObj]); */

    setEvents((prevState) => {
      return [...prevState, newObj];
    });
  };

  console.log(data);
  return (
    <>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomePage data={events} />
      <form action="" onSubmit={submit}>
        <input
          type="text"
          placeholder="add event"
          onChange={(e) => setText(e.target.value)}
        />
        <button type="submit">submit</button>
      </form>
    </>
  );
}

export const getServerSideProps = async () => {
  const { events_categories } = await import("../data/data.json");
  console.log(events_categories);
  return {
    props: { data: events_categories },
  };
};
